# Création de la première base de données #

In [28]:
import pandas as pd
df = pd.read_csv('result_trie.csv')
df_naf = pd.read_csv('output_icpe_with_NAF.csv')
df_naf.rename(columns={'entete_nom': 'Nom',
                   'entete_siret': 'Siret',
                   'situation_administrative_code_rubrique': 'Code_Rubrique',
                   'entete_statut_seveso': 'Statut_Seveso',
                   'situation_administrative_libelle_rubrique': 'Libelle_rubrique',
                   'situation_administrative_volume' : 'Volume'}, inplace=True)
df_naf = df_naf.drop(columns=['entete_etat_d_activite', 'entete_regime_en_vigueur_de_l_etablissement_2', 
                                            'entete_ied_-_mtd', 'situation_administrative_alinea'])

/var/folders/_l/z5vqwjnn06l67wbqpt8pt73c0000gn/T/ipykernel_7595/2296589397.py:2: DtypeWarning: Columns (0: cd_insee, 1: cd_postal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('result_trie.csv')

In [29]:
# Nettoyage du csv pour faire un merge plus propre ultérieurement
df.rename(columns={'code_aiot': 'num_etablissement'}, inplace=True)
print(df.columns)

Index(['num_etablissement', 'nom_ets', 'x', 'y', 'adresse', 'cd_insee',
       'cd_postal', 'commune', 'code_naf', 'lib_naf', 'num_siret', 'cd_regime',
       'lib_regime', 'seveso', 'lib_seveso', 'Description du code ICPE',
       'ICPE_A', 'ICPE_E', 'ICPE_D', 'date_modification',
       'derniere_inspection'],
      dtype='str')

In [30]:
df.drop(columns=['x', 'y', 'date_modification', 'seveso', 'lib_seveso','date_modification', 'cd_insee'], inplace=True)
df.head()

,num_etablissement,nom_ets,adresse,cd_postal,commune,code_naf,lib_naf,num_siret,cd_regime,lib_regime,Description du code ICPE,ICPE_A,ICPE_E,ICPE_D,derniere_inspection
0,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,Secteur de la Marquette,33240,Gauriaguet,41.0,Construction de bâtiments,4.229897e+13,A,Autorisation,Solides inflammables,1450.0,NaN,NaN,NaN
1,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,Secteur de la Marquette,33240,Gauriaguet,41.0,Construction de bâtiments,4.229897e+13,A,Autorisation,Alcools de bouche d'origine agricole,NaN,NaN,4755.0,NaN
2,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,Secteur de la Marquette,33240,Gauriaguet,41.0,Construction de bâtiments,4.229897e+13,A,Autorisation,"Liquides comburants catégorie 1, 2 ou 3",NaN,NaN,4441.0,NaN
3,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,Secteur de la Marquette,33240,Gauriaguet,41.0,Construction de bâtiments,4.229897e+13,A,Autorisation,Liquides inflammables de catégorie 2 ou catégo...,NaN,NaN,4331.0,NaN
4,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,Secteur de la Marquette,33240,Gauriaguet,41.0,Construction de bâtiments,4.229897e+13,A,Autorisation,Liquides inflammables de catégorie 1,NaN,NaN,4330.0,NaN

In [31]:
df_naf.head()

,num_etablissement,Nom,Siret,Statut_Seveso,derniere_date_inspection,Code_Rubrique,Libelle_rubrique,situation_administrative_regime_autorise,Volume,code_naf,nomenclatureActivitePrincipaleEtablissement
0,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,3.434035e+13,Non Seveso,2026-01-26,2782,Autres traitements biologiques de déchets non ...,Autorisation,NaN,38.32Z,NAFRev2
1,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,3.434035e+13,Non Seveso,2026-01-26,3532,Valorisation de déchets non dangereux,Autorisation,518.000 t/j,38.32Z,NAFRev2
2,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,Non Seveso,NaN,1436,Liquides combustibles de point éclair compris ...,Déclaration avec contrôle,900.000 t,41.10A,NAFRev2
3,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,Non Seveso,NaN,1450,Solides inflammables,Autorisation,150.000 t,41.10A,NAFRev2
4,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,Non Seveso,NaN,1510,Entrepôts couverts soumis à EE systématique,Autorisation,NaN,41.10A,NAFRev2