In [2]:
import numpy as np
import pandas as pd

In [ ]:
with open(r"StockEtablissement_utf8.csv", 'r', encoding='utf-8') as f:
    print(f.read(500))  # Affiche les 500 premiers caractères

siren,nic,siret,statutDiffusionEtablissement,dateCreationEtablissement,trancheEffectifsEtablissement,anneeEffectifsEtablissement,activitePrincipaleRegistreMetiersEtablissement,dateDernierTraitementEtablissement,etablissementSiege,nombrePeriodesEtablissement,complementAdresseEtablissement,numeroVoieEtablissement,indiceRepetitionEtablissement,dernierNumeroVoieEtablissement,indiceRepetitionDernierNumeroVoieEtablissement,typeVoieEtablissement,libelleVoieEtablissement,codePostalEtablissement,libelleC

In [5]:
#lecture du doc pour le calcul de flux
df=pd.read_csv("output_icpe_with_NAF.csv",sep=',',encoding='utf-8')
df.head()

,num_etablissement,entete_nom,entete_siret,entete_etat_d_activite,entete_regime_en_vigueur_de_l_etablissement_2,entete_statut_seveso,entete_ied_-_mtd,derniere_date_inspection,situation_administrative_code_rubrique,situation_administrative_alinea,situation_administrative_libelle_rubrique,situation_administrative_regime_autorise,situation_administrative_volume,code_naf
0,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,3.434035e+13,En exploitation avec titre,Autorisation,Non Seveso,Oui,2026-01-26,2782,NaN,Autres traitements biologiques de déchets non ...,Autorisation,NaN,38.32Z
1,39,COLLECTES VALORISATION ENERGIE DECHETS - COVED,3.434035e+13,En exploitation avec titre,Autorisation,Non Seveso,Oui,2026-01-26,3532,NaN,Valorisation de déchets non dangereux,Autorisation,518.000 t/j,38.32Z
2,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,En exploitation avec titre,Autorisation,Non Seveso,Non,NaN,1436,2,Liquides combustibles de point éclair compris ...,Déclaration avec contrôle,900.000 t,41.10A
3,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,En exploitation avec titre,Autorisation,Non Seveso,Non,NaN,1450,1,Solides inflammables,Autorisation,150.000 t,41.10A
4,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,4.229897e+13,En exploitation avec titre,Autorisation,Non Seveso,Non,NaN,1510,1,Entrepôts couverts soumis à EE systématique,Autorisation,NaN,41.10A

In [15]:
result=pd.read_csv("result_trie.csv",sep=',')
result.head()

C:\Users\esthe\AppData\Local\Temp\ipykernel_9180\680235651.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  result=pd.read_csv("result_trie.csv",sep=',')

,code_aiot,nom_ets,x,y,adresse,cd_insee,cd_postal,commune,code_naf,lib_naf,...,cd_regime,lib_regime,seveso,lib_seveso,Description du code ICPE,ICPE_A,ICPE_E,ICPE_D,date_modification,derniere_inspection
0,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,432849,6444403,Secteur de la Marquette,33183.0,33240,Gauriaguet,41.0,Construction de bâtiments,...,A,Autorisation,3.0,Non Seveso,Solides inflammables,1450.0,NaN,NaN,2026/05/06 00:00:00,NaN
1,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,432849,6444403,Secteur de la Marquette,33183.0,33240,Gauriaguet,41.0,Construction de bâtiments,...,A,Autorisation,3.0,Non Seveso,Alcools de bouche d'origine agricole,NaN,NaN,4755.0,2026/05/06 00:00:00,NaN
2,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,432849,6444403,Secteur de la Marquette,33183.0,33240,Gauriaguet,41.0,Construction de bâtiments,...,A,Autorisation,3.0,Non Seveso,"Liquides comburants catégorie 1, 2 ou 3",NaN,NaN,4441.0,2026/05/06 00:00:00,NaN
3,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,432849,6444403,Secteur de la Marquette,33183.0,33240,Gauriaguet,41.0,Construction de bâtiments,...,A,Autorisation,3.0,Non Seveso,Liquides inflammables de catégorie 2 ou catégo...,NaN,NaN,4331.0,2026/05/06 00:00:00,NaN
4,2,PITCH IMMO SNC : HEXAHUB : hangars logistiques...,432849,6444403,Secteur de la Marquette,33183.0,33240,Gauriaguet,41.0,Construction de bâtiments,...,A,Autorisation,3.0,Non Seveso,Liquides inflammables de catégorie 1,NaN,NaN,4330.0,2026/05/06 00:00:00,NaN