In [1]:
import pandas as pd
import numpy as np
dfbis = pd.read_csv("output_icpe.csv", dtype={'entete_siret': str})
df = pd.read_csv("output_icpe_clean.csv", dtype={'entete_siret': str})
dfbis.head()

,num_etablissement,entete_nom,entete_siret,entete_etat_d_activite,entete_regime_en_vigueur_de_l_etablissement_2,entete_statut_seveso,entete_ied_-_mtd,situation_administrative_code_rubrique,situation_administrative_alinea,situation_administrative_libelle_rubrique,situation_administrative_regime_autorise,situation_administrative_volume
0,3012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,NaN,NaN,NaN,NaN,NaN
1,3012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,NaN,NaN,NaN,NaN,NaN
2,3012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,NaN,NaN,NaN,NaN,NaN
3,3012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,NaN,NaN,NaN,NaN,NaN
4,3012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,NaN,NaN,NaN,NaN,NaN

In [43]:
df = df.dropna(subset=['situation_administrative_code_rubrique'])
num_etab = df["num_etablissement"].astype(str)
df['situation_administrative_code_rubrique'] = df['situation_administrative_code_rubrique'].astype(int)
df['num_etablissement'] = num_etab.str.rjust(10, '0')
df.to_csv("output_icpe_clean.csv", index=False)
df.head()

,num_etablissement,entete_nom,entete_siret,entete_etat_d_activite,entete_regime_en_vigueur_de_l_etablissement_2,entete_statut_seveso,entete_ied_-_mtd,situation_administrative_code_rubrique,situation_administrative_alinea,situation_administrative_libelle_rubrique,situation_administrative_regime_autorise,situation_administrative_volume
0,0003012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,2770,NaN,Traitement thermique de déchets dangereux,Autorisation,NaN
1,0003012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,2771,NaN,Traitement thermique de déchets non dangereux,Autorisation,NaN
2,0003012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,3110,NaN,Combustion,Autorisation,130.000 MW
3,0003012003,NOVAWOOD,82181865500010,En exploitation avec titre,Autorisation,Non Seveso,Oui,3520,b,pour les déchets dangereux,Autorisation,432.000 t/j
4,0003012007,FERME EOLIENNE LA HOTTE,80366621300019,En exploitation sans titre,Autorisation,Non Seveso,Non,2980,1,Eoliennes de + de 50 m,Autorisation,NaN

In [44]:
columns_to_use = ['siret', 'activitePrincipaleEtablissement']
df_NAF = pd.read_csv('StockEtablissement_utf8.csv', usecols=columns_to_use, sep=',')

# 1. Renommer la colonne dans df_NAF
df_NAF.rename(columns={'siret': 'entete_siret'}, inplace=True)

# 2. Forcer le type 'str' (texte) dans les DEUX DataFrames pour éviter l'erreur
df_NAF['entete_siret'] = df_NAF['entete_siret'].astype(str)
df['entete_siret'] = df['entete_siret'].astype(str)

In [45]:
df = df.merge(df_NAF, on='entete_siret', how='left')
df.rename(columns={'activitePrincipaleEtablissement': 'code_naf'}, inplace=True)
df.to_csv("output_icpe_with_NAF.csv", index=False)
print("Le CSV a été nettoyé et enregisté avec succès ! ;)")

Le CSV a été nettoyé et enregisté avec succès ! ;)